name: develer-science
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter=1.0*
  - jupyterlab=0.34*
  - matplotlib=3.0*
  - notebook=5.7*
  - pandas=0.23*
  - scikit-learn=0.20*
  - certifi=2018*
  - bokeh=0.12*
  - pip:
    - keras>=2.2.4
    - tensorflow>=1.8
    - Pillow~=5.3
